export interface IName {
  name: string;
  gender: "male" | "female" | "neutral";
  origin: string;
  variants: string[];
}

export const names: IName[] = [
  {
    name: "Алiсiа",
    gender: "female",
    origin: "(Алиса)",
    variants: ["Алiса", "Алia", "Аля", "Ciя", "Лiсiа", "Алiс", "Елiс"],
  },
  {
    name: "Асеул[iа]",
    gender: "neutral",
    origin: "Аса + Ула",
    variants: ["Аселя", "Лiя"],
  },
  {
    name: "Мiлен[а]",
    gender: "neutral",
    origin: "Мiлене / (Милана)",
    variants: ["Мiлана", "Мiлена", "Мiля", "Мiлiа", "Iлен"],
  },
  {
    name: "Лайнпветер",
    gender: "male",
    origin: "Лайна + Пветер",
    variants: ["Лайнпвето", "Лайнтер"],
  },
  {
    name: "Скаярст",
    gender: "male",
    origin: "Скайо + Ярст",
    variants: ["Скай", "Скаяст", "Кайа"],
  },
  {
    name: "Скайо",
    gender: "male",
    origin: "Скайо",
    variants: ["Скай", "Аiйо"],
  },
  {
    name: "Люсiк",
    gender: "male",
    origin: "Люсiк",
    variants: ["Люс", "Сiк"],
  },
  {
    name: "Мiголia",
    gender: "female",
    origin: "Амiгорiа / (Ангелина)",
    variants: ["Мiга", "Голiа", "Лiа", "Мiлiа", "Мiля"],
  },
  {
    name: "Вiсел[ia]",
    gender: "neutral",
    origin: "Вiсела",
    variants: [
      "Вiла",
      "Вiлiа",
      "Лiа",
      "Сiлiа",
      "Вiля",
      "Сiля",
      "Селiа",
      "Вiся",
      "Вiс",
      "Ел",
      "Ель",
      "Вiсi",
      "Iсi",
    ],
  },
  {
    name: "Вiголia",
    gender: "female",
    origin: "(Виселия) / (Миголия)",
    variants: [
      "Вiла",
      "Вiлiа",
      "Лiа",
      "Гiлiа",
      "Голiа",
      "Вiля",
      "Гiля",
      "Геля",
      "Велiа",
      "Вiся",
    ],
  },
  {
    name: "Калiн[а]",
    gender: "neutral",
    origin: "Калiна",
    variants: ["Калiна", "Кален", "Каль", "Каля", "Калiа", "Кля"],
  },
  {
    name: "Лайвалайн[а]",
    gender: "neutral",
    origin: "Лайва + Лайна",
    variants: ["Лайя", "Лайвн", "Лаван"],
  },
  {
    name: "Iрiс",
    gender: "female",
    origin: "",
    variants: ["Iрс", "Рiс", "Iрена", "Iрi"],
  },
  {
    name: "Вайлепв",
    gender: "neutral",
    origin: "",
    variants: ["Вайл", "Лепв", "Валпв"],
  },
  {
    name: "Ейдзз",
    gender: "male",
    origin: "Ейдзз",
    variants: ["Ейд"],
  },
  {
    name: "Анастасiа",
    gender: "female",
    origin: "(Анастасия)",
    variants: ["Настiа", "Настя", "Стiа", "Сiа", "Настя", "Натiа"],
  },
  {
    name: "Максiм",
    gender: "male",
    origin: "(Максим)",
    variants: ["Макс", "Сiм"],
  },
  {
    name: "Лесiан",
    gender: "male",
    origin: "(лес)",
    variants: ["Лес", "Лесiн", "Сiн", "Сiан", "Сан"],
  },
  {
    name: "Зепвiр[iа]",
    gender: "neutral",
    origin: "Зепвiр",
    variants: ["Зепвiря", "Зепв[iа]", "Пвiр[я]", "Пвiрiа", "Рiа", "Рiя"],
  },
  {
    name: "Пваворл[iа]",
    gender: "neutral",
    origin: "Пвавор",
    variants: ["Пвавор", "Лiа", "Лiя", "Пворлiя", "Рiя"],
  },
  {
    name: "Нiколан[а]",
    gender: "neutral",
    origin: "(Николай)",
    variants: ["Нiк", "Нiкi", "Колан[iа]", "Ан[iа]"],
  },
  {
    name: "Ремел[iа]",
    gender: "neutral",
    origin: "(Роман)",
    variants: ["Рем", "Мел[iа]"],
  },
  {
    name: "Крiст[iа]",
    gender: "neutral",
    origin: "",
    variants: ["Крiс", "Крiстi"],
  },
  {
    name: "Пвенол[iа]",
    gender: "neutral",
    origin: "",
    variants: ["Пвен[iа]", "Пвеня", "Пвенол[iа]"],
  },
  {
    name: "Неркон",
    gender: "male",
    origin: "",
    variants: ["Нерк", "Нерон"],
  },
  {
    name: "Крайер",
    gender: "male",
    origin: "",
    variants: ["Край", "Крей", "Раiр"],
  },
  {
    name: "Евелiн[а]",
    gender: "neutral",
    origin: "",
    variants: ["Ева", "Лiн[а]", "Евiн[а]"],
  },
  {
    name: "Iнiлин",
    gender: "male",
    origin: "",
    variants: ["Ini", "Лiн", "Iнiл"],
  },
  {
    name: "Веснia",
    gender: "female",
    origin: "Весна",
    variants: ["Веся", "Вiснiа", "Нiа"],
  },
  {
    name: "Крiмн[а]",
    gender: "neutral",
    origin: "",
    variants: ["Крiм", "Крiн", "Крiмн", "Рiмн[iа]", "Крiя", "Нiа"],
  },
  {
    name: "Роз[iа]",
    gender: "neutral",
    origin: "Роза / (Роза)",
    variants: ["Розi", "Розя", "Зiа"],
  },
  {
    name: "Ангелiна",
    gender: "female",
    origin: "(Ангелина)",
    variants: [
      "Лiна",
      "Анлiна",
      "Ангеля",
      "Ангелiа",
      "Гелiна",
      "Геля",
      "Гелiа",
      "Ангела",
      "Лiа",
    ],
  },
  {
    name: "Несс[iа]",
    gender: "neutral",
    origin: "Неßа",
    variants: ["Неся", "Нессiа", "Нiся"],
  },
  {
    name: "Ньюберт[iа]",
    gender: "female",
    origin: "(Роберт)",
    variants: ["Нью", "Берд", "Нюбiрд", "Тiа", "Нюбертя", "Нютя", "Нютiа"],
  },
  {
    name: "Мiлiпвер",
    gender: "male",
    origin: "",
    variants: ["Мiл", "Мiлiпв", "Мiлiпвер", "Лiпвер"],
  },
  {
    name: "Валентiн[а]",
    gender: "male",
    origin: "(Валентин)",
    variants: ["Вал", "Валя", "Валiа", "Валент"],
  },
  {
    name: "Мiкронезiйка",
    gender: "neutral",
    origin: "",
    variants: [
      "Мiкронейзi",
      "Мiкронезi",
      "Нейзi",
      "Незi",
      "Нейзiа",
      "Незя",
      "Зiа",
    ],
  },
  {
    name: "Любовiа",
    gender: "female",
    origin: "(Любовь)",
    variants: ["Любiа", "Любовiа", "Любовя", "Люба", "Любiа"],
  },
  {
    name: "Любiн[iа]",
    gender: "neutral",
    origin: "(Любовь)",
    variants: ["Люб[а]", "Любя", "Любiа", "Люнiа", "Бiн[я]"],
  },
  {
    name: "Лювамiн",
    gender: "male",
    origin: "",
    variants: ["Лювiм", "Люв", "Вамiн", "Лювiм"],
  },
  {
    name: "Айдар",
    gender: "male",
    origin: "(Айдар)",
    variants: ["Аiдар", "Адар", "Айдiр", "Айд"],
  },
  {
    name: "Рiнат[а]",
    gender: "neutral",
    origin: "(Ринат)",
    variants: ["Рiн[я]", "Рiнiа", "Нат"],
  },
  {
    name: "Монiк[а]",
    gender: "neutral",
    origin: "(Моника)",
    variants: ["Нiк[а]", "Мон[я]", "Монiа"],
  },
  {
    name: "Александр[iа]",
    gender: "neutral",
    origin: "(Александра)",
    variants: [
      "Алекс[iа]",
      "Рiа",
      "Лекс[iа]",
      "Сасса",
      "Сандр[а]",
      "Сiа",
      "Андр[iа]",
      "Кся",
    ],
  },
  {
    name: "Осiн[iа]",
    gender: "neutral",
    origin: "Осiна / Осiнь",
    variants: ["Осi", "Ося", "Ася", "Асiа", "Сiя", "Сiн[iа]", "Сiня"],
  },
  {
    name: "Бiрезiа",
    gender: "female",
    origin: "Бiреза",
    variants: ["Бiр[iа]", "Зiя", "Резiа", "Резя", "Рiз", "Бiрзiя"],
  },
  {
    name: "Блюрiс",
    gender: "male",
    origin: "",
    variants: ["Рiз", "Рiс", "Блюр"],
  },
  {
    name: "Нiол[iа]",
    gender: "female",
    origin: "",
    variants: [
      "Нiл[iа]",
      "Нiя",
      "Нiля",
      "Оля",
      "Олiя",
      "Ниол[а]",
      "Олiа",
      "Iлiа",
    ],
  },
  {
    name: "Пвiалiа",
    gender: "female",
    origin: "Пвiала",
    variants: ["Пвiлiа", "Пвеня", "Iлiа", "Iля", "Пвiля", "Лiя", "Лiа"],
  },
  {
    name: "Пвлорiа",
    gender: "female",
    origin: "Пвлора",
    variants: ["Лорiа", "Лоря", "Пвлоря", "Рiя", "Рiа", "Iлорiа"],
  },
  {
    name: "Пветерiа",
    gender: "female",
    origin: "Пветер",
    variants: [
      "Пвiлiа",
      "Пвеня",
      "Iлiа",
      "Iля",
      "Пвiля",
      "Лiя",
      "Лiа",
      "Пвiтя",
      "Терiа",
      "Рiа",
      "Рiя",
      "Теря",
    ],
  },
];
